services:

  mongo:
    image: mongo:7
    container_name: dockerbdfestivos
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: festivos
    networks:
      - redcalendario
    restart: unless-stopped

  express-api:
    build: .
    container_name: dockerapifestivos
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://mongo:27017/festivos
      PORT: 8080
    depends_on:
      - mongo
    networks:
      - redcalendario
    restart: unless-stopped

networks:
  redcalendario:
    external: true

volumes:
  mongo-data:
